[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pychannellib"
version = "1.0.0"
description = "A simple Python event call and creation system."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "GRAND"}
    {name = "MattButBetter"}
]
keywords = ["channels", "events", "triggers", "keybinds", "keyboard"]

dependencies = [
    "keyboard"
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
